# Generated by Django 2.1 on 2018-08-21 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Atleta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('sobrenome', models.CharField(max_length=50)),
                ('apelido', models.CharField(max_length=50)),
                ('data_nascimento', models.DateField(null=True)),
                ('local_nascimento', models.CharField(max_length=50)),
                ('descricao', models.TextField()),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='atletas')),
            ],
            options={
                'verbose_name': 'Atleta',
                'verbose_name_plural': 'Atletas',
                'db_table': 'atleta',
            },
        ),
        migrations.CreateModel(
            name='Jogo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adversario', models.CharField(max_length=50)),
                ('data', models.DateField()),
                ('local', models.CharField(max_length=50)),
                ('arbitragem', models.CharField(blank=True, max_length=80, null=True)),
                ('escudo_adversario', models.ImageField(blank=True, default='comuns/sem_escudo.png', null=True, upload_to='jogos')),
                ('placar_real', models.IntegerField(blank=True, null=True)),
                ('placar_adversario', models.IntegerField(blank=True, null=True)),
                ('resumo', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Jogo',
                'verbose_name_plural': 'Jogos',
                'db_table': 'jogo',
            },
        ),
        migrations.CreateModel(
            name='JogoAtleta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atleta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jogo.Atleta')),
                ('jogo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jogo.Jogo')),
            ],
        ),
    ]
