# Generated by Django 2.2.2 on 2019-09-16 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jogo', '0003_fatura'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fatura',
            name='status',
        ),
        migrations.AlterField(
            model_name='fatura',
            name='atleta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jogo.Atleta'),
        ),
    ]
